var base_url = 'https://yixsu.com/public/index.php';

var urls = {
    page_submit:base_url+'/Apimanagerrecommend/laugh/page_submit.html',
    make_qrcode:base_url+'/Apimanagerrecommend/laugh/make_qrcode.html',
    img_upload:base_url+'/Apimanagerrecommend/laugh/img_upload.html',
    my_tmplist:base_url+'/Apimanagerrecommend/laugh/my_tmplist.html',
    tmp_info:base_url+'/Apimanagerrecommend/laugh/tmp_info.html',
    alltmplist:base_url+'/Apimanagerrecommend/laugh/alltmplist.html',
    add_tmp:base_url+'/Apimanagerrecommend/laugh/add_tmp.html',
    del_tmp:base_url+'/Apimanagerrecommend/laugh/del_tmp.html',
    mypages:base_url+'/Apimanagerrecommend/laugh/mypages.html',
    del_page:base_url+'/Apimanagerrecommend/laugh/del_page.html',
    page_info:base_url+'/Apimanagerrecommend/laugh/page_info.html',
    info_modify:base_url+'/Apimanagerrecommend/User/info_modify.html',
    sys_tips:base_url+'/Apimanagerrecommend/laugh/sys_tips.html',
    contact:base_url+'/Apimanagerrecommend/laugh/contact.html',
    suggest_list:base_url+'/Apimanagerrecommend/laugh/suggest_list.html',
    add_suggest:base_url+'/Apimanagerrecommend/laugh/add_suggest.html',
    page_detail_info:base_url+'/Apimanagerrecommend/laugh/page_detail_info.html',
    sign:base_url+'/Apimanagerrecommend/laugh/sign.html',
    cutprice_sign:base_url+'/Apimanagerrecommend/laugh/cutprice_sign.html',
    cutprice_cut:base_url+'/Apimanagerrecommend/laugh/cutprice_cut.html',
    praise_sign:base_url+'/Apimanagerrecommend/laugh/praise_sign.html',
    praise_praise:base_url+'/Apimanagerrecommend/laugh/praise_praise.html',
    fightgroup_sign:base_url+'/Apimanagerrecommend/laugh/fightgroup_sign.html',
    fightgroup_sign_pay:base_url+'/Apimanagerrecommend/pay/wechat_pay_create.html',
    fightgroup_join:base_url+'/Apimanagerrecommend/laugh/fightgroup_join.html',
    fightgroup_join_pay:base_url+'/Apimanagerrecommend/pay/wechat_pay_create.html',
    quick_buy:base_url+'/Apimanagerrecommend/laugh/quick_buy.html',
    vote:base_url+'/Apimanagerrecommend/laugh/vote.html',
    user_pages:base_url+'/Apimanagerrecommend/laugh/user_pages.html',
    del_user_page:base_url+'/Apimanagerrecommend/laugh/del_user_page.html',
    remark_sign:base_url+'/Apimanagerrecommend/laugh/remark_sign.html',
    verify_code:base_url+'/Apimanagerrecommend/laugh/verify_code.html',
    send_code:base_url+'/Apimanagerrecommend/laugh/send_code.html',
    pick_verify:base_url+'/Apimanagerrecommend/laugh/pick_verify.html',
    user_phones:base_url+'/Apimanagerrecommend/user/user_phones.html',
    statistics_point:base_url+'/Apimanagerrecommend/laugh/statistics_point.html',
    ads:base_url+'/Apimanagerrecommend/ads/index.html',
}

module.exports = {
    urls: urls
}
